spring:
  application:
    name: gateway
 
server:
  port: 8861
 
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
 
zuul:
  routes:
    order:
      path: /order/**
      serviceId: order-service
#      url: http://localhost:8763
    user:
      path: /auth/**
      serviceId: auth-service
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 10000
 
order-service:
  ribbon:
    ReadTimeout: 10000
    ConnectTimeout: 10000