spring:
  profiles:
    active: native #告诉服务,我现在要启用本地配置(优先考虑采用工程目录resources下配置)
  application:
    name: config-server #名称
  cloud:
    config:
      server:
        native:
          search-locations:  D:/workspaces/springcloud/avidm-cloud/avidm-cloud-configserver/configs
        #git:
          #uri: F:/gits/git1.git #uri
          #search-paths: /** #配置文件目录
      #label: master
      #username: solider #github账号
      # password: 123456 #github密码
 
server:
  port: 8961
 
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/