#auth
auth-server: http://localhost:8762/auth
security:
  basic:
    enabled: false
  oauth2:
    client:
      client-id: client
      client-secret: secret
      scope: user_info
      access-token-uri: ${auth-server}/oauth/token
      user-authorization-uri: ${auth-server}/oauth/authorize
    resource:
      token-info-uri: ${auth-server}/oauth/check_token